In [1]:
import torch
from schnetpack.datasets import QM9
import schnetpack as spk
import os
from my_config import config_args
from MyModel.HGCN import RegModel
import optimizers
import numpy as np
import logging
import time
from tqdm import tqdm

# 获得训练数据

In [2]:
qm9data = QM9('./data/qm9.db', download=True,load_only=[QM9.U0])
qm9split = './data/qm9split'
print(len(qm9data))

133885


In [3]:
train, val, test = spk.train_test_split(
        data=qm9data,
        num_train=20000,
        num_val=10000,
        split_file=os.path.join(qm9split, "split20000.npz"),
    )
print(len(train),len(test),len(val))

20000 103885 10000


In [4]:
train_loader = spk.AtomsLoader(train, batch_size=400, shuffle=False)
val_loader = spk.AtomsLoader(val, batch_size=10)

In [5]:
from manifolds.hyperboloid import Hyperboloid
manifold = Hyperboloid()
size = (1,3,2)
input = torch.ones(size)
c = 1
input = torch.concat([torch.zeros((1,3,1)),input],dim=2)
input = manifold.proj_tan0(input,c)
print(input)

tensor([[[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]]])


In [6]:
input = manifold.expmap0(input,c)

In [7]:
import sys
import json
class obj(object):
    def __init__(self, dict_):
        self.__dict__.update(dict_)
args = json.loads(json.dumps(config_args), object_hook=obj)

model = RegModel(args)
optimizer = getattr(optimizers, args.optimizer)(params=model.parameters(), lr=args.lr,
                                                    weight_decay=args.weight_decay)
lr_scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer,
    step_size=args.lr_reduce_freq,
    gamma=float(args.gamma)
)
tot_params = sum([np.prod(p.size()) for p in model.parameters()])
logging.info(f"Total number of parameters: {tot_params}")
device = torch.device('cuda')
# Train model
t_total = time.time()
model = model.to(device)
loss_fun = torch.nn.MSELoss()
for epoch in range(args.epochs):
    loss_sum,n,t = 0,0,0.0
    counter = 0
    for input in tqdm(train_loader):
        counter+=1
        # if counter>10:
        #     sys.exit(0)
        for key in input:
            input[key] = input[key].to(torch.device('cuda'))
        t = time.time()
        model.train()
        optimizer.zero_grad()
        y_hat = model(input)
        # print('y_hat',y_hat[:2])
        # print('input[QM9.U0]',input[QM9.U0][:2])
        loss = loss_fun(y_hat,input[QM9.U0])


        # print(loss)
        loss.backward()
        loss_sum += loss
        n += 1
        if args.grad_clip is not None:
            max_norm = float(args.grad_clip)
            all_params = list(model.parameters())
            for param in all_params:
                torch.nn.utils.clip_grad_norm_(param, max_norm)
        optimizer.step()
    lr_scheduler.step()
    if (epoch + 1) % args.log_freq == 0:
        str = " ".join(['Epoch: {:04d}'.format(epoch + 1),
                               'lr: {}'.format(lr_scheduler.get_last_lr()[0]),
                               'loss: {:.4f}'.format(loss_sum/n),
                               'time: {:.4f}s'.format(time.time() - t)
                               ])
        print(str)
        logging.info(str)
        curvatures = list(model.get_submodule('curvatures'))
        print(curvatures)



    # if (epoch + 1) % args.eval_freq == 0:
    #     model.eval()
    #     embeddings = model.encode(data['features'], data['adj_train_norm'])
    #     val_metrics = model.compute_metrics(embeddings, data, 'val')
    #     if (epoch + 1) % args.log_freq == 0:
    #         logging.info(" ".join(['Epoch: {:04d}'.format(epoch + 1), format_metrics(val_metrics, 'val')]))
    #     if model.has_improved(best_val_metrics, val_metrics):
    #         best_test_metrics = model.compute_metrics(embeddings, data, 'test')
    #         best_emb = embeddings.cpu()
    #         if args.save:
    #             np.save(os.path.join(save_dir, 'embeddings.npy'), best_emb.detach().numpy())
    #         best_val_metrics = val_metrics
    #         counter = 0
    #     else:
    #         counter += 1
    #         if counter == args.patience and epoch > args.min_epochs:
    #             logging.info("Early stopping")
    #             break

    """
    Epoch: 0027 lr: 0.01 loss: 1459.0519 time: 0.0866s

    """

100%|██████████| 50/50 [00:28<00:00,  1.78it/s]


Epoch: 0001 lr: 0.01 loss: 51961592.0000 time: 0.0675s
[Parameter containing:
tensor([1.0640], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9447], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9659], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0014], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0280], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0337], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0220], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8107], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9005], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0002 lr: 0.01 loss: 5395310.5000 time: 0.0674s
[Parameter containing:
tensor([1.0635], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9426], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9663], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0762], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9837], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0745], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9929], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8082], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9121], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0003 lr: 0.01 loss: 5256723.5000 time: 0.0973s
[Parameter containing:
tensor([1.0667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9639], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9593], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0965], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9628], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0210], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0432], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8081], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9106], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.88it/s]


Epoch: 0004 lr: 0.01 loss: 3669008.5000 time: 0.1218s
[Parameter containing:
tensor([1.0607], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9988], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8704], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.1097], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9383], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9237], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0323], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8732], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8623], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0005 lr: 0.01 loss: 938591.5000 time: 0.0954s
[Parameter containing:
tensor([1.1821], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9528], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9018], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9607], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0617], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8756], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.1289], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8041], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8514], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0006 lr: 0.01 loss: 490984.0625 time: 0.1157s
[Parameter containing:
tensor([1.3043], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9348], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8980], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8146], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.1834], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8589], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.2048], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7778], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8558], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0007 lr: 0.01 loss: 234344.7500 time: 0.0724s
[Parameter containing:
tensor([1.3830], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8855], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8650], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7223], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.2818], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9782], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.1752], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7779], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8557], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0008 lr: 0.01 loss: 82450.2812 time: 0.0706s
[Parameter containing:
tensor([1.4222], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8236], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7450], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7441], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.2804], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0054], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9964], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8015], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8420], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.92it/s]


Epoch: 0009 lr: 0.01 loss: 19665.3633 time: 0.0694s
[Parameter containing:
tensor([1.4188], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8235], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7188], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3032], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0171], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9936], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8024], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8396], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0010 lr: 0.01 loss: 14339.8213 time: 0.0720s
[Parameter containing:
tensor([1.4057], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8186], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7122], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6959], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3198], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9945], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8459], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8018], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8362], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0011 lr: 0.01 loss: 10043.6562 time: 0.0768s
[Parameter containing:
tensor([1.3904], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8230], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7476], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6514], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3446], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9941], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8013], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7998], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8332], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0012 lr: 0.01 loss: 7194.0205 time: 0.0820s
[Parameter containing:
tensor([1.3899], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8419], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7209], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6019], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3637], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0059], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7930], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8311], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:25<00:00,  1.92it/s]


Epoch: 0013 lr: 0.01 loss: 5018.5815 time: 0.0640s
[Parameter containing:
tensor([1.3881], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8465], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6964], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5824], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3524], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0220], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7822], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8298], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0014 lr: 0.01 loss: 3277.6233 time: 0.0745s
[Parameter containing:
tensor([1.4009], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8352], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6886], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6121], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3455], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0415], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7764], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8283], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.92it/s]


Epoch: 0015 lr: 0.01 loss: 1851.2947 time: 0.0796s
[Parameter containing:
tensor([1.3975], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8350], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6817], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5779], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3593], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0273], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7750], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8266], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0016 lr: 0.01 loss: 950.5666 time: 0.0855s
[Parameter containing:
tensor([1.3959], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8382], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6910], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5731], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3627], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0227], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7766], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8250], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0017 lr: 0.01 loss: 520.9180 time: 0.0742s
[Parameter containing:
tensor([1.4010], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8248], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6879], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5747], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3722], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0178], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7777], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8237], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0018 lr: 0.01 loss: 252.7327 time: 0.0705s
[Parameter containing:
tensor([1.4044], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8243], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6863], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5715], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3656], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0212], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7783], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8229], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:27<00:00,  1.80it/s]


Epoch: 0019 lr: 0.01 loss: 144.3450 time: 0.1211s
[Parameter containing:
tensor([1.4076], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8218], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6938], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5624], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3639], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0263], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7791], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8225], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0020 lr: 0.005 loss: 91.6831 time: 0.0760s
[Parameter containing:
tensor([1.4098], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8178], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6979], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5628], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3649], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0222], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7797], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8221], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0021 lr: 0.005 loss: 55.5648 time: 0.1204s
[Parameter containing:
tensor([1.4086], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8185], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6977], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5619], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3657], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0213], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7800], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8220], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.92it/s]


Epoch: 0022 lr: 0.005 loss: 43.7010 time: 0.0891s
[Parameter containing:
tensor([1.4100], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8168], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6990], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5616], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3652], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0235], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7801], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8219], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0023 lr: 0.005 loss: 34.9663 time: 0.0771s
[Parameter containing:
tensor([1.4098], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8178], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7000], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5619], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3658], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0258], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7803], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8218], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0024 lr: 0.005 loss: 28.3694 time: 0.0643s
[Parameter containing:
tensor([1.4099], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8182], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6993], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5615], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3657], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0245], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7804], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8217], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0025 lr: 0.005 loss: 23.0853 time: 0.0885s
[Parameter containing:
tensor([1.4100], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8184], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6973], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5629], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3665], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0267], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7805], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8216], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0026 lr: 0.005 loss: 18.6058 time: 0.0760s
[Parameter containing:
tensor([1.4101], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8176], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6969], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5640], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3664], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0249], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7806], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8215], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0027 lr: 0.005 loss: 15.2358 time: 0.1217s
[Parameter containing:
tensor([1.4103], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8168], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6975], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5639], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3658], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0227], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7807], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8215], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0028 lr: 0.005 loss: 12.8558 time: 0.0818s
[Parameter containing:
tensor([1.4102], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8176], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6973], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5643], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3669], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0226], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7807], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8214], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0029 lr: 0.005 loss: 11.1428 time: 0.1202s
[Parameter containing:
tensor([1.4103], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8183], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6973], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5641], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3666], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0230], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7808], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8214], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.88it/s]


Epoch: 0030 lr: 0.005 loss: 9.8900 time: 0.1209s
[Parameter containing:
tensor([1.4107], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8183], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6971], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5640], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3662], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0209], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7808], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8213], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0031 lr: 0.005 loss: 8.9367 time: 0.0838s
[Parameter containing:
tensor([1.4110], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8186], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6975], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5640], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3657], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0222], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7808], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8213], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0032 lr: 0.005 loss: 8.2241 time: 0.0849s
[Parameter containing:
tensor([1.4105], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8182], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6976], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5643], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3660], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0213], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8213], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.87it/s]


Epoch: 0033 lr: 0.005 loss: 7.6886 time: 0.0870s
[Parameter containing:
tensor([1.4106], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8183], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6975], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5641], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3666], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0204], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8213], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0034 lr: 0.005 loss: 7.2637 time: 0.0775s
[Parameter containing:
tensor([1.4106], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8184], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6971], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5646], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3664], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0200], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0035 lr: 0.005 loss: 6.8913 time: 0.0729s
[Parameter containing:
tensor([1.4103], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8180], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6972], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5648], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0207], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0036 lr: 0.005 loss: 6.5820 time: 0.0852s
[Parameter containing:
tensor([1.4104], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8178], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6975], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5650], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0215], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0037 lr: 0.005 loss: 6.3720 time: 0.0723s
[Parameter containing:
tensor([1.4105], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8180], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6962], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5650], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3676], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0212], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0038 lr: 0.005 loss: 6.2069 time: 0.1267s
[Parameter containing:
tensor([1.4107], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8176], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6949], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5658], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3677], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0243], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0039 lr: 0.005 loss: 5.9804 time: 0.1084s
[Parameter containing:
tensor([1.4111], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8176], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6960], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5653], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0244], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0040 lr: 0.0025 loss: 5.7917 time: 0.0740s
[Parameter containing:
tensor([1.4110], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8170], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6941], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5668], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3677], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0250], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0041 lr: 0.0025 loss: 5.3276 time: 0.0642s
[Parameter containing:
tensor([1.4110], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8166], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6944], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3677], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0247], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0042 lr: 0.0025 loss: 5.3354 time: 0.1209s
[Parameter containing:
tensor([1.4112], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8168], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6948], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5663], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0268], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0043 lr: 0.0025 loss: 5.2844 time: 0.0841s
[Parameter containing:
tensor([1.4111], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8168], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6946], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5665], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3678], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0268], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0044 lr: 0.0025 loss: 5.2363 time: 0.0772s
[Parameter containing:
tensor([1.4108], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8160], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6947], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3673], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0267], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0045 lr: 0.0025 loss: 5.2160 time: 0.0832s
[Parameter containing:
tensor([1.4110], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8161], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6944], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5670], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0278], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0046 lr: 0.0025 loss: 5.2207 time: 0.0842s
[Parameter containing:
tensor([1.4113], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8161], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6945], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5669], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3678], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0294], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0047 lr: 0.0025 loss: 5.2163 time: 0.1210s
[Parameter containing:
tensor([1.4113], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8163], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6942], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5673], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0310], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0048 lr: 0.0025 loss: 5.1293 time: 0.0839s
[Parameter containing:
tensor([1.4110], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8161], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6937], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3677], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0308], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0049 lr: 0.0025 loss: 4.9542 time: 0.0728s
[Parameter containing:
tensor([1.4111], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8162], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6939], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5670], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3682], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0319], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0050 lr: 0.0025 loss: 4.7889 time: 0.0787s
[Parameter containing:
tensor([1.4115], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8161], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6942], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5673], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3684], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0308], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0051 lr: 0.0025 loss: 4.6736 time: 0.0852s
[Parameter containing:
tensor([1.4120], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8164], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6943], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5671], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3683], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0301], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0052 lr: 0.0025 loss: 4.5949 time: 0.1218s
[Parameter containing:
tensor([1.4119], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8167], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6935], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3682], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0284], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.88it/s]


Epoch: 0053 lr: 0.0025 loss: 4.5285 time: 0.0732s
[Parameter containing:
tensor([1.4120], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8170], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6929], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5678], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3678], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0281], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0054 lr: 0.0025 loss: 4.4545 time: 0.1360s
[Parameter containing:
tensor([1.4117], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8176], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6923], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5682], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0280], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0055 lr: 0.0025 loss: 4.3653 time: 0.0734s
[Parameter containing:
tensor([1.4115], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8174], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6929], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5679], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3670], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0269], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0056 lr: 0.0025 loss: 4.2785 time: 0.0768s
[Parameter containing:
tensor([1.4118], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8172], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6929], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5680], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3672], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0267], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0057 lr: 0.0025 loss: 4.2069 time: 0.1210s
[Parameter containing:
tensor([1.4120], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8174], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6928], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5683], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3674], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0255], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0058 lr: 0.0025 loss: 4.1461 time: 0.0725s
[Parameter containing:
tensor([1.4119], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8177], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6927], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5685], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3678], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0247], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.88it/s]


Epoch: 0059 lr: 0.0025 loss: 4.0888 time: 0.1198s
[Parameter containing:
tensor([1.4122], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8175], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6922], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5690], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3676], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0228], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0060 lr: 0.00125 loss: 4.0359 time: 0.0889s
[Parameter containing:
tensor([1.4124], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8172], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6918], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5692], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0218], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:27<00:00,  1.79it/s]


Epoch: 0061 lr: 0.00125 loss: 3.9604 time: 0.0721s
[Parameter containing:
tensor([1.4125], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8173], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6914], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5693], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0217], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0062 lr: 0.00125 loss: 3.8647 time: 0.0990s
[Parameter containing:
tensor([1.4124], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8171], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6918], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5693], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3675], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0215], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0063 lr: 0.00125 loss: 3.8427 time: 0.1362s
[Parameter containing:
tensor([1.4124], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8169], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6919], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5693], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3672], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0208], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0064 lr: 0.00125 loss: 3.8190 time: 0.0675s
[Parameter containing:
tensor([1.4124], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8171], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6919], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5695], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3673], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0217], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.89it/s]


Epoch: 0065 lr: 0.00125 loss: 3.7973 time: 0.1134s
[Parameter containing:
tensor([1.4122], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8175], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6920], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5694], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3669], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0215], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.91it/s]


Epoch: 0066 lr: 0.00125 loss: 3.7765 time: 0.0865s
[Parameter containing:
tensor([1.4122], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8181], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6920], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5693], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0215], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0067 lr: 0.00125 loss: 3.7545 time: 0.0811s
[Parameter containing:
tensor([1.4120], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8183], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6921], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5693], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3667], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0216], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


100%|██████████| 50/50 [00:26<00:00,  1.90it/s]


Epoch: 0068 lr: 0.00125 loss: 3.7267 time: 0.0836s
[Parameter containing:
tensor([1.4122], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8184], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.6919], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.5692], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3665], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0224], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8011], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.7809], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8212], device='cuda:0', requires_grad=True)]


 12%|█▏        | 6/50 [00:03<00:26,  1.69it/s]


KeyboardInterrupt: 

In [ ]:
# from manifolds.hyperboloid import Hyperboloid
# import torch
# size = (2,5,10)
# a = 2*torch.ones(size)
# a = torch.concat([torch.zeros((2,5,1)),a],dim=2)
# print(a)
# hyper = Hyperboloid()
# c = 1
# a_H = hyper.expmap0(a,c)  #
# print(a_H)
# a_H_p = hyper.proj(a_H,c)  #对双曲空间的向量没有影响
# print(a_H_p)

# a_tan = hyper.logmap0(a_H,c)
# print(a_tan)
#
# a_tan_p = hyper.proj_tan0(a_tan,c)  #  对已经在o点切空间的向量没有影响
# print(a_tan_p)

# a_tan_a = hyper.logmap(a_H,a_H,c)  # 向量在其切空间是0
# print(a_tan_a)



