In [1]:
import torch
from manifolds.hyperboloid import Hyperboloid
manifold = Hyperboloid()
size = (1,3,2)
input = torch.tensor(   [[[1., 8.],
                          [3., 2.],
                          [-1e5, 1e5]]])
c = 1e-4   # c约接近0，双曲空间的数据缩放越小，能表示的数字越大
input = torch.concat([torch.zeros((1,3,1)),input],dim=2)

In [4]:
tensors = torch.tensor([[1,2,3],
                        [1,5,6]])
tensors = tensors.unsqueeze(2).expand(-1,-1,3)
print(tensors[1,2])

tensor([6, 6, 6])


In [6]:
t = torch.tensor([-666666,-1e-10,999999,1e-10])
print(t)
t = torch.clamp(t,min=-1e-6,max=100)
print(t)

tensor([-6.6667e+05, -1.0000e-10,  1.0000e+06,  1.0000e-10])
tensor([-1.0000e-06, -1.0000e-10,  1.0000e+02,  1.0000e-10])


In [2]:
input = manifold.proj_tan0(input,c)
print(input)

tensor([[[ 0.0000e+00,  1.0000e+00,  8.0000e+00],
         [ 0.0000e+00,  3.0000e+00,  2.0000e+00],
         [ 0.0000e+00, -1.0000e+05,  1.0000e+05]]])


In [3]:
input_H0 = manifold.expmap0(input,c)
print(input_H0)

tensor([[[ 1.0033e+02,  1.0011e+00,  8.0087e+00],
         [ 1.0007e+02,  3.0006e+00,  2.0004e+00],
         [ 1.6345e+08, -1.1558e+08,  1.1558e+08]]])


In [4]:
input_tan0 = manifold.logmap0(input_H0,c)
print(input_tan0)


tensor([[[ 0.0000e+00,  9.9999e-01,  7.9999e+00],
         [ 0.0000e+00,  2.9999e+00,  2.0000e+00],
         [ 0.0000e+00, -1.0607e+03,  1.0607e+03]]])


In [5]:
o = torch.zeros(size)
o = torch.concat([torch.zeros((1,3,1)),o],dim=2)
o = manifold.proj_tan0(o,c)
o = manifold.expmap0(o,c)
print(o)  # 原点是[1/根号k,0,...,0]

tensor([[[100.,   0.,   0.],
         [100.,   0.,   0.],
         [100.,   0.,   0.]]])


In [6]:
input_t = manifold.logmap(o,input_H0,c)
print(input_t)

tensor([[[ 0.0000,  0.8771,  7.0165],
         [ 0.0000,  2.9999,  2.0000],
         [ 0.0000, -5.0000,  5.0000]]])


In [7]:
input_t = manifold.expmap(input_t,o,c)
print(input_t)

tensor([[[100.2501,   0.8778,   7.0223],
         [100.0650,   3.0006,   2.0004],
         [100.2501,  -5.0042,   5.0042]]])


In [8]:
input_H0_tan = manifold.logmap(o,input_H0,c)
print(input_H0_tan)

tensor([[[ 0.0000,  0.8771,  7.0165],
         [ 0.0000,  2.9999,  2.0000],
         [ 0.0000, -5.0000,  5.0000]]])
