In [81]:
import torch
from manifolds.hyperboloid import Hyperboloid
manifold = Hyperboloid()
size = (1,3,2)
input = torch.tensor(   [[[1., 1.],
                          [2., 2.],
                          [6, 6]]])
c = 1
input = torch.concat([torch.zeros((1,3,1)),input],dim=2)

In [82]:
input = manifold.proj_tan0(input,c)
print(input)

tensor([[[0., 1., 1.],
         [0., 2., 2.],
         [0., 6., 6.]]])


In [83]:
input_H0 = manifold.expmap0(input,c)
print(input_H0)

tensor([[[2.1782e+00, 1.3683e+00, 1.3683e+00],
         [8.4890e+00, 5.9608e+00, 5.9608e+00],
         [2.4215e+03, 1.7122e+03, 1.7122e+03]]])


In [84]:
input_tan0 = manifold.logmap0(input_H0,c)
print(input_tan0)


tensor([[[0., 1., 1.],
         [0., 2., 2.],
         [0., 6., 6.]]])


In [85]:
o = torch.zeros(size)
o = torch.concat([torch.zeros((1,3,1)),o],dim=2)
o = manifold.proj_tan0(o,c)
o = manifold.expmap0(o,c)
print(o)  # 原点是[1/根号k,0,...,0]

tensor([[[1., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.]]])


In [86]:
input_t = manifold.logmap(o,input_H0,c)
print(input_t)

tensor([[[0., 1., 1.],
         [0., 2., 2.],
         [0., 5., 5.]]])


In [87]:
input_t = manifold.expmap(input_t,o,c)
print(input_t)

tensor([[[  2.1782,   1.3683,   1.3683],
         [  8.4890,   5.9608,   5.9608],
         [588.7028, 416.2751, 416.2751]]])


In [88]:
input_H0_tan = manifold.logmap(o,input_H0,c)
print(input_H0_tan)

tensor([[[0., 1., 1.],
         [0., 2., 2.],
         [0., 5., 5.]]])
